### ISSUE TITLE
Supplementary Data 5. A summary of target gene prediction of strong enhancer(EnhA)

### ISSUE THREAD

**Issue by lx-1011** [zhypan/Functional-Annotation-of-Pig#1]
Dear @zhypan ,
    Thank you for all the annotation files of pigs. It is my pleasures to read your paper " Pig genome functional annotation enhances the biological interpretation of complex traits and human disease",  which make me know more about function genome of pigs. But I have some question about the document interpretation:
Supplementary Data 5. A summary of target gene prediction of strong enhancer(EnhA)
![image](https://user-images.githubusercontent.com/47030888/154503993-50b23382-f2ab-4519-9330-b1406fd03ad5.png)
what does 2th, 3th, 5th and 6th row mean?

Thanks and wish you all the best
Li Xin

**Comment by zhypan** [comment]
Hi Lixin,

        Following are:
         'regulator', 'rho', 'pval', 'gene', 'distance', 'qval'

**Comment by zhypan** [comment]
1 - Enhancer region
2 - Spearman correlation of H3K27ac and RNA-seq across samples
3 - p-value for correlation
4 - Gene ID
5 - Distance of enhancer from TSS
6 - q-value for correlation

**Comment by lx-1011** [comment]
> 
Thank you !
