### ISSUE TITLE
how to draw the TSS enrichment

### ISSUE THREAD

**Issue by zhoudreames** [zhypan/Functional-Annotation-of-Pig#2]
![image](https://user-images.githubusercontent.com/54714639/169650990-5b63e330-72a5-4a88-88f4-fc49a131edc5.png)
Hi，In your article, The TSS enrichment plot is wonderful, and we wanted to draw it followed your method, could you provide me code ? thanks~

**Comment by zhoudreames** [comment]
@zhypan I am so sorry to disturb you, do you help me ? thanks ~

**Comment by zhypan** [comment]
computeMatrix scale-regions \
-R /group/zhougrp/zhangyuan/genome/pig/part_change_esemb100/protein_coding_esemble100.bed \
-S "DeepTools/H3K27ac_"$tissue"_vs_Input_ZScores.bw" "DeepTools/H3K27me3_"$tissue"_vs_Input_ZScores.bw" "DeepTools/H3K4me1_"$tissue"_vs_Input_ZScores.bw" "DeepTools/H3K4me3_"$tissue"_vs_Input_ZScores.bw" "DeepTools/ATAC_"$tissue"_ZScores.bw" \
-a 2500 -b 2500 \
-out "ComputeMatrix/"$tissue"_protein_coding_region.mat.gz" \
-p 24 \
--skipZeros


plotProfile -m "ComputeMatrix/"$tissue"_protein_coding_region.mat.gz" \
-out "Figures/"$tissue"_scale_protein_coding_density_plot.PDF" \
--perGroup \
--colors red gray yellow green pink \
--samplesLabel H3K27ac H3K27me3 H3K4me1 H3K4me3 ATAC \
-z ""

**Comment by zhoudreames** [comment]
Thanks，but i used the averge epigenetic mark signal for all tissue to draw this plot, how to gain the bw files?  now ,I only got the bw files of the single sample.

**Comment by zhypan** [comment]
--outFileNameData

output the data for each tissue, then do the average.

**Comment by zhypan** [comment]
https://deeptools.readthedocs.io/en/develop/content/tools/plotProfile.html

**Comment by zhoudreames** [comment]
thanks so much~

**Comment by zhoudreames** [comment]
I am so sorry to disturb you again, I ask you a final problem,  how to get the  "$tissuevs_Input_ZScores.bw" files, when I run this code: bamCoverage -p 5 --normalizeUsing RPKM -b ${OUTPUT}/${NAME}_AC_makedup_sorted.chrY.bam  -o ${OUTPUT}/${NAME}_AC_makedup_sorted.chrY.bw, the y axis of data is more than 2000, which is inconsistent with your article result. Did I not subtract the input coverage or did I use the wrong normalize method ？

**Comment by zhypan** [comment]
First, you need to use the input control if you have. Second, you need do the score. https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zscore.html
